# Generated by Django 4.1.7 on 2023-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.IntegerField(),
        ),
    ]
