# Generated by Django 4.1.2 on 2023-05-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_process_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.project')),
            ],
        ),
    ]
