# Generated by Django 4.1.2 on 2023-05-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_processament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processament',
            old_name='prioridade',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='processament',
            old_name='data_submissao',
            new_name='submition_date',
        ),
        migrations.AddField(
            model_name='processament',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
